name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: "${{ secrets.REPOSITORY }}"
  # github.repository as <account>/<repo>
  IMAGE_NAME: "jmhtestimagetodelete"
  IMGTAG: "latest"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.JF_USER }}
        password: ${{ secrets.JF_PASS }}
        logout: false

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Push the docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
